### ISSUE TITLE
Error while building (libinput.h: No such file)

### ISSUE THREAD

**Issue by NikitinGs** [DreamMaoMao/hycov#67]
OS: OpenSUSE Tumbleweed
Installed latest Hyprland from git
Full log: pastebin.com/LLdKVXtF

**Comment by woojiq** [comment]
Maybe this should be a separate issue, but I want to mention that I also can't compile with the latest Hyprland https://github.com/hyprwm/Hyprland/tree/cbadf3e3f31ab5ad5d192daac5f2ca930d08b8fb. Although I was able to compile with Hyprland v0.34.0

**Comment by DreamMaoMao** [comment]
> Maybe this should be a separate issue, but I want to mention that I also can't compile with the latest Hyprland https://github.com/hyprwm/Hyprland/tree/cbadf3e3f31ab5ad5d192daac5f2ca930d08b8fb:
> 
> ```
> error: 'class CCompositor' has no member named 'windowFromCursor'
> ```
> 
> Although I was able to compile with Hyprland v0.34.0
> 
> Logs (NixOs)
this commit broken somethiing ,
https://github.com/hyprwm/Hyprland/commit/cbadf3e3f31ab5ad5d192daac5f2ca930d08b8fb 

has fixed in :

https://github.com/DreamMaoMao/hycov/commit/d07068bd8767a940bf554e1f6d39f2f1691b0703

**Comment by NikitinGs** [comment]
@DreamMaoMao sorry if I missed something but what is the solution to my issue?

**Comment by DreamMaoMao** [comment]
> pastebin.com/LLdKVXtF


Your problem is not a problem with hcov itself. This is a common compilation problem. You need to install the development library pointed out in the error report.

**Comment by NikitinGs** [comment]
> > pastebin.com/LLdKVXtF
> 
> Your problem is not a problem with hcov itself. This is a common compilation problem. You need to install the development library pointed out in the error report.

I thought so, but libinput is already a requirement for Hyprland, and it is installed on my system
Packages I have: libinput-devel, libinput-tools (installed that just in case), libinput-udev, libinput10, xf86-input-libinput, xf86-input-libinput-devel

**Comment by woojiq** [comment]
Can you compile Hyprland without the plugin?

**Comment by NikitinGs** [comment]
> Can you compile Hyprland without the plugin?

Sorry @woojiq, I don't think that I follow you, wdym by 'without the plugin'?

**Comment by DreamMaoMao** [comment]
If your environment is messy, I recommend using hyprpm to install  plugin.

```
$ hyprpm update
$ hyprpm add https://github.com/DreamMaoMao/hycov
$ hyprpm enable hycov
```

add  this to your hyprland.conf  and relogin hyprland
```
exec-once = hyprpm reload 
```

refer:
https://wiki.hyprland.org/Plugins/Using-Plugins/#hyprpm

**Comment by NikitinGs** [comment]
Does not seem to work @DreamMaoMao, it gives the same error

**Comment by DreamMaoMao** [comment]
sorry. Maybe you're having a problem finding headers, and I don't have any ideas.
